// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpQuWYuIVpI6pphLcFX5FH1hVnDTPIYI',
    appId: '1:1040407952215:android:7ba26341d8422dde511c12',
    messagingSenderId: '1040407952215',
    projectId: 'taskflow-app-ded90',
    storageBucket: 'taskflow-app-ded90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCasu1hQvpyaa38xzk5MmZkBTmny4Sqdis',
    appId: '1:1040407952215:ios:785114f1963ec774511c12',
    messagingSenderId: '1040407952215',
    projectId: 'taskflow-app-ded90',
    storageBucket: 'taskflow-app-ded90.firebasestorage.app',
    androidClientId: '1040407952215-dtk3bd18ejbcb9espn898iuucb4295n3.apps.googleusercontent.com',
    iosClientId: '1040407952215-tq9a5q7pkukcu6d6v5pioj7lq8utrhu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTodoApp',
  );

}